#!/bin/sh

# Get launch directory
CWD=`pwd`
LAUNCH_DIRECTORY=`eval dirname $0`
cd $LAUNCH_DIRECTORY
LAUNCH_DIRECTORY=`pwd`
cd $CWD

# Make sure JAVA_HOME is in front of all other paths
if [ "${JAVA_HOME}" != "" ]; then
  PATH=${JAVA_HOME}/bin:${PATH}
fi

# Run java command with "atm.dir" property
java -Datm.dir="${LAUNCH_DIRECTORY}" -jar "${LAUNCH_DIRECTORY}/lib/atm.jar" ${1+"$@"}
